# @format

version: "3.8"

services:
  database:
    container_name: bookstore-database
    image: postgres:latest
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres

  
