version: "3.8"

services:
  bookworm-database-test:
    container_name: bookworm-database-test
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - bookworm-net
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres

networks:
  bookworm-net:
    driver: bridge
