version: "2" # specify docker-compose version

# Define the services/containers to be run
services:
  keycloak:
    image: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
